markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
domain: http://smartmz.github.io
title: SmartMZ的BLOG
description: 积累
author: SmartMZ
email: miaoze612@gmail.com
github: 

config:
  js_dir:
  img_dir:
  css_dir:
